### ISSUE TITLE
Method POST support

### ISSUE THREAD

**Issue by ludwiktrammer** [ethaizone/Bootstrap-Confirmation#17]
I don't think there is much need for confirming actions that doesn't have any side-effects. And all actions that _have_ side-effects should always be performed using HTTP method POST. This plugin is absolutely beautiful, but without support for POST it is not very useful in the real world, and I'd argue it encourages bad behaviour (i.e. using GET for actions with side-effects).

**Comment by DeadDuck** [comment]
+1
I searched long time for a simple way to submit a form with this to delete an item.  Deleting it using a GET link is not an option as I follow best practices, and it can be very problematic on the user side. I've found an alternative plugin which can confirm on submit buttons, but it's not as beautiful & customizable as this one...
It would be great to have this feature on this one, attach it to a submit button and go.

**Comment by DeadDuck** [comment]
I added the feature and created a pull request. Please see:
https://github.com/tavicu/bs-confirmation/pull/19
