### ISSUE TITLE
have bootstrap, have jquery, dont see popup

### ISSUE THREAD

**Issue by tmkctm** [ethaizone/Bootstrap-Confirmation#20]
I have bootstrap and jquery, but it isnt clear to me if i am using this awesome module right. I have a div, yes? on the div i placed .attr('data-toggle', 'confirmation') and i also place .confirmation({onConfirm: function(){})
but when i hover over my div, all i see in the console is Uncaught TypeError: Cannot read property 'timeout' of undefined
I dont even click, and when i do click nothing happens. it isnt clear from documentation if what i did is good so.. .please help?

**Comment by almaruf** [comment]
@ethaizone   - This worked , thanks

**Comment by walkerdepaula** [comment]
@ethaizone This wordked, but now i have this issue :( 
https://github.com/tavicu/bs-confirmation/issues/25
