### ISSUE TITLE
Delete on laravel

### ISSUE THREAD

**Issue by anggardagasta** [ethaizone/Bootstrap-Confirmation#21]
How can I use this to delete on laravel?

here is my code

		href 			: '../public/transportation/delete/6',

6 is the primary key,,so how can I get this PK on laravel?

**Comment by raulp** [comment]
@anggardagasta , set a valid URL , and once the user confirms, that will trigger an HTTP request to that URL. Where you can delete or whatever you're doing. This is not related to the plugin, this is basic coding.
