### ISSUE TITLE
i cant pass a value on confirm

### ISSUE THREAD

**Issue by JohnnyB3** [ethaizone/Bootstrap-Confirmation#25]
how do i pass a value when someone selects the yes(confirm) popup???
nothing i do works
i did get it to say confirm(in the alert in the code) so i know its working, i just cant read any values at all
what am i doing wrong please

[code]
 $(".remove_record").confirmation({
        trigger: 'click',
        singleton: true,
        btnOkLabel: '<i class="fa fa-check-circle-o"></i> Yes',
        btnCancelLabel: '<i class="fa fa-times"></i> No',
        placement: 'top',
        onConfirm: function(){
      		//var $embellishment = $(this);
      		//alert($embellishment.data("data-f_id"));
      		var id_data = $(this).attr('data-f_id');
      		console.log("id: "+id_data);
      		console.log("href: "+$(this).attr('href'));
        	//alert("Confirmed");
        	//var idx = $(this).data('f_id');
        	//var idx = $(this).attr('data-f_id');
        	//alert('remove - '+idx);
      		$('.remove_record').confirmation('hide');
        }
    });

	<a href="#?facility_id='.$items['Facility_ID'].'" class="btn btn-danger btn-sm remove_record" style="color:white;font-weight:bold;" name="remove_record" id="remove_record" style="cursor:pointer" data-f_id="'.$items['Facility_ID'].'" data-title="DELETE: '.$items['Facility_Name'].'. Are you sure? This CANNOT be undone!" ><i class="fa fa-trash-o fa-fw"></i> Delete</a>

[/code]

i tried using the data-toggle="confirmation" but that didnt work either

thank you in advance for any help you may provide

**Comment by franazo** [comment]
Prueba con  $(this).attr('f_id');

**Comment by dikkeduif** [comment]
If anyone is still looking for a possible solution to this, I solved it like this. It's more a hack than a real solution, but it works.

When you click the <a> element, the confirmation box element is added after the clicked <a> element. So you can find the closest 'popover' element, which is the container for the confirmation box, and you move one element up to take the actual <a> element.

So for example:

HTML:
```
<a data-toggle='confirmation' href='' data-id='$a' class='btn btn-info'>Regenerate token</a>
```

After you trigger to confirmation box you get:
```
<a data-toggle='confirmation' href='' data-id='$a' class='btn btn-info'>Regenerate token</a>
<div class="popover fade top in" style="top: ...; left: ...; display: block;">....</div>
```

So in order to get the original <a> element you can do:

Code:
```
$('[data-toggle="confirmation"]').confirmation({
        placement: 'top',
        onConfirm: function() {
            var myElement = $(this).closest('.popover').prev();
            console.log(myElement.attr('data-id'));
        }
       ...
});
```

**Comment by ethaizone** [comment]
I'm sorry that I don't make code support for this case. Solution from @dikkeduif is correct. I will not fix it because it come long way to fix and nature of popover that will create new element as sibling.

**Comment by giorgoc** [comment]
the easiest way is to save into a hidden field the value prior firing up the confirmation popover. Once confirmed, you can easily grab the value from there. No _hacky_ workarounds, no methods that could be deprecated into the near future. Works like a charm! :)

**Comment by HarveyEV** [comment]
I have a similar problem where I am trying to use this to confirm an action prior to firing an ajax submission. My link looks like this:

`<a class="btn btn-sm btn-default btn-danger remove-item" type="button" data-href="remove-entry.json?type=orgunit&amp;id=16" data-prompt="confirmation" data-toggle="tooltip" title="" data-original-title="Delete">
                            <i class="fa fa-remove"></i>
                        </a>`

And my ajax looks like below. However it is not intercepting the submission.:
`
$('[data-prompt="confirmation"]').confirmation({
onConfirm: function(event) {
var myElement = $(this).closest('.remove-item').prev();
console.log(myElement.attr('data-href'));
$('.formmessages').hide();
event.preventDefault();
$.ajax({
type: 'GET',
url: myElement.attr('data-href'),
async: false,
dataType: 'json', 
 ...
`

Any ideas?
