### ISSUE TITLE
Confirmation only showing in the second click

### ISSUE THREAD

**Issue by rogeroliveira84** [ethaizone/Bootstrap-Confirmation#28]
Hi the code below has a problem, it just shows the popup when I click twice in my button, how should I initialize it? If I don't ask the button.confirmation('show') it is not showing the popup with the initilization.

            $('#divSetStatus button').on("click", function (e) {
                e.preventDefault();
               
                // Check if there is an item selected
                var totalSelected = TableManaged.GetSelectedRowsTotal($('#datatableList'));
                if (totalSelected > 0) {

                    // select button pressed
                    var newStatus = e.target.value;
                    var button = $('button[value=' + newStatus + ']');

                    // initialize Bootstrap.Confirmation plugin
                    // if I put here: button.confirmation('destroy')           it shows, but with when I cancel, next time I have to press twice to run the onConfirm

                    button.confirmation({
                        singleton: true,
                        popout: true,
                        onConfirm: function () {
                                     alert('');
                            });
                        }
                    });
                    button.confirmation('show');  // IF I DON'T PUT THIS, IT DIDN'T SHOW the confirmation
                }
            });

**Comment by ethaizone** [comment]
Please create example in http://jsfiddle.net/ or send link of example page that you found problem. I can read code but I don't know html structure or you use another js library or not. You can have some problem if you declare confirmation twice on same element.

**Comment by rogeroliveira84** [comment]
Hi, I have fixed the problem, I was not using it correctly.

**Comment by rogeroliveira84** [comment]
Thanks for your answer.

**Comment by rodrigoporcionato** [comment]
How to fix? I have same problem?

**Comment by MarlonWilkes** [comment]
@rodrigoporcionato
I alse had same problem,and I found that it not support bootstrap 3...
I should read author's readme first...

**Comment by Kryptonit3-zz** [comment]
Here is a repo that works without this issue

https://github.com/tavicu/bs-confirmation

**Comment by mwaschkowski** [comment]
toggle works best, fixed my same issue
