### ISSUE TITLE
Why you don't want to register your library with bower?

### ISSUE THREAD

**Issue by sharikovvladislav** [ethaizone/Bootstrap-Confirmation#37]
Hey,

Why you don't want to use bower?

It will be very simple to instal for other peoples. One thing they need is to write `bower install <name>`. All dependencies of your library will be downloaded too (you specify it).

I can help you with it if you need (actually you don't it is really simple)

**Comment by mezhmal** [comment]
Did you see at https://libraries.io/bower/bootstrap-confirmation2 ?

**Comment by sharikovvladislav** [comment]
Yep, thank you . I already found it and used it in my project.

Closed.
